name:                cloudinary-types
version:             0.1.0
description:         Cloudinary API types
license:             MIT
license-file:        LICENSE
author:              damianfral
maintainer:          huevofritopamojarpan@gmail.com


library :
 
  source-dirs     : src

  exposed-modules : 

    - Data.Cloudinary

  dependencies :

    - aeson
    - base
    - envy
    - generic-lens
    - lens
    - mtl
    - protolude
    - text
    - http-api-data

  default-extensions :

    - ConstraintKinds
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedLabels
    - OverloadedStrings
    - RankNTypes
    - TypeApplications
    - TypeOperators

