name: cloudinary
version: 0.2.0
description: Cloudinary API
license: MIT
license-file: LICENSE
author: damianfral
maintainer: huevofritopamojarpan@gmail.com

ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

dependencies:
  - aeson
  - base
  - envy
  - generic-lens
  - http-api-data
  - http-client-tls
  - lens
  - protolude
  - resourcet
  - servant
  - servant-client
  - text

executables :
  cloudinary-cli :
    source-dirs: src
    main: Main.hs

library:
  source-dirs: src


