name         : cloudinary
version      : 0.1.0
description  : Cloudinary API
license      : MIT
license-file : LICENSE
author       : damianfral
maintainer   : huevofritopamojarpan@gmail.com

dependencies :

  - aeson
  - base
  - envy
  - generic-lens
  - http-api-data
  - http-client-tls
  - lens
  - monad-control
  - mtl
  - protolude
  - resourcet
  - servant
  - servant-client
  - text
  - transformers-base

default-extensions :

  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - QuantifiedConstraints
  - RankNTypes
  - TypeApplications
  - TypeOperators


executables :

  cloudinary-cli :

    source-dirs : src
    main : Main.hs


library :

  source-dirs     : src

  exposed-modules :

    - Data.Cloudinary
    - Network.Cloudinary

