name:                cloudinary-io
version:             0.1.0
description:         Cloudinary API client implementation
license:             MIT
license-file:        LICENSE
author:              damianfral
maintainer:          huevofritopamojarpan@gmail.com


library :
 
  source-dirs     : src

  exposed-modules : 

    - Network.Cloudinary

  dependencies :

    - aeson
    - base
    - cloudinary-types
    - envy
    - generic-lens
    - http-client-tls
    - lens
    - monad-control
    - mtl
    - protolude
    - servant
    - servant-client
    - text
    - transformers-base

  default-extensions :
    
    - GeneralizedNewtypeDeriving
    - ConstraintKinds
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - NoImplicitPrelude
    - OverloadedLabels
    - OverloadedStrings
    - TypeApplications
    - TypeOperators
    - MultiParamTypeClasses
    - RankNTypes
    - QuantifiedConstraints
    - DerivingStrategies

