name:                cloudinary-cli
version:             0.1.0
description:         Cloudinary API CLI
license:             MIT
license-file:        LICENSE
author:              damianfral
maintainer:          huevofritopamojarpan@gmail.com


executables :
  cloudinary :
 
    source-dirs : src
    main        : CLI.hs

    dependencies :

      - aeson
      - base
      - cloudinary-io
      - cloudinary-types
      - envy
      - generic-lens
      - http-client-tls
      - lens
      - mtl
      - protolude
      - resourcet
      - servant
      - servant-client
      - text

    default-extensions :
      
      - GeneralizedNewtypeDeriving
      - ConstraintKinds
      - DataKinds
      - DeriveAnyClass
      - DeriveGeneric
      - FlexibleContexts
      - FlexibleInstances
      - NoImplicitPrelude
      - OverloadedLabels
      - OverloadedStrings
      - TypeApplications
      - TypeOperators
      - MultiParamTypeClasses
      - RankNTypes
      - QuantifiedConstraints
      - DerivingStrategies

